version: '1'
services:
  redis:
    image: 'redis:latest'
    expose: 
      - '6397:6397'
  server:
    build:
      dockerfile: server.Dockerfile
      context: ./server
    environment:
      - APIKEY=$APIKEY
      - APITOKEN=$APITOKEN
      - LOGLEVEL=1
      - CLIENTPORT=5173
      - REDISKEY=
      - REDISURL=redis:6397
    volumes:
      - .:/server
    ports: 
      - '8080:8080'
  client:
    build:
      dockerfile: client.Dockerfile
      context: ./client
    volumes:
      - .:/client
    ports: 
      - '5173:5173'