version: '1'
services:
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: server.Dockerfile
      context: ./server
    environment:
      - APIKEY=$APIKEY
      - APITOKEN=$APITOKEN
      - LOGLEVEL=$LOGLEVEL
      - CLIENTURL=$CLIENTURL
      - REDISKEY=$REDISKEY
      - REDISURL=$REDISURL
    volumes:
      - .:/server
  client:
    build:
      dockerfile: client.Dockerfile
      context: ./client
    volumes:
      - .:/client
  nginx:
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client