version: '1'
services:
  redis:
    image: 'redis:latest'
    ports: 
      - '6397:6397'
  server:
    build:
      dockerfile: server.Dockerfile
      context: ./server
    environment:
      - APIKEY=$APIKEY
      - APITOKEN=$APITOKEN
      - LOGLEVEL=$LOGLEVEL
      - CLIENTURL=$CLIENTURL
      - REDISKEY=$REDISKEY
      - REDISURL=$REDISURL
    volumes:
      - .:/server
    ports: 
      - '8080:8080'
  client:
    build:
      dockerfile: client.Dockerfile
      context: ./client
    volumes:
      - .:/client
    ports: 
      - '5173:5173'
  nginx:
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - client