// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version v0.3.0 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/discord-gophers/goapi-gen/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

// Cast defines model for Cast.
type Cast []Person

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// MovieDetails defines model for MovieDetails.
type MovieDetails struct {
	Backdrop string   `json:"backdrop"`
	Date     string   `json:"date"`
	Genres   []string `json:"genres"`
	Homepage string   `json:"homepage"`
	Name     string   `json:"name"`
	Overview string   `json:"overview"`
	Poster   string   `json:"poster"`
	Rating   float64  `json:"rating"`
	Runtime  int      `json:"runtime"`
}

// MovieList defines model for MovieList.
type MovieList struct {
	Page       int            `json:"page"`
	Results    []MoviePreview `json:"results"`
	TotalPages int            `json:"totalPages"`
}

// MoviePreview defines model for MoviePreview.
type MoviePreview struct {
	Date     string  `json:"date"`
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	Overview string  `json:"overview"`
	Poster   string  `json:"poster"`
	Rating   float64 `json:"rating"`
}

// Person defines model for Person.
type Person struct {
	Character string `json:"character"`
	Name      string `json:"name"`
	Picture   string `json:"picture"`
}

// Review defines model for Review.
type Review struct {
	Content string `json:"content"`
	Rating  string `json:"rating"`
}

// ReviewList defines model for ReviewList.
type ReviewList struct {
	Page       int      `json:"page"`
	Results    []Review `json:"results"`
	TotalPages int      `json:"totalPages"`
}

// Video defines model for Video.
type Video struct {
	Link    string `json:"link"`
	Title   string `json:"title"`
	Trailer bool   `json:"trailer"`
}

// VideoList defines model for VideoList.
type VideoList []Video

// GetMovieReviewsParams defines parameters for GetMovieReviews.
type GetMovieReviewsParams struct {
	// page number
	Page string `json:"page"`
}

// SearchMovieParams defines parameters for SearchMovie.
type SearchMovieParams struct {
	// Query string
	QueryString string `json:"queryString"`

	// page number
	Page string `json:"page"`
}

// GetCategoryParams defines parameters for GetCategory.
type GetCategoryParams struct {
	// page number
	Page string `json:"page"`
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
// It may also be instantiated directly, for the purpose of responding with a single status code.
type Response struct {
	body        interface{}
	Code        int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.Code)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(code int) *Response {
	resp.Code = code
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// GetMovieCastJSON200Response is a constructor method for a GetMovieCast response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieCastJSON200Response(body Cast) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetMovieCastJSON400Response is a constructor method for a GetMovieCast response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieCastJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetMovieCastJSON500Response is a constructor method for a GetMovieCast response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieCastJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetMovieCastJSON502Response is a constructor method for a GetMovieCast response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieCastJSON502Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        502,
		contentType: "application/json",
	}
}

// GetMovieDetailsJSON200Response is a constructor method for a GetMovieDetails response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieDetailsJSON200Response(body MovieDetails) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetMovieDetailsJSON400Response is a constructor method for a GetMovieDetails response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieDetailsJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetMovieDetailsJSON500Response is a constructor method for a GetMovieDetails response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieDetailsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetMovieDetailsJSON502Response is a constructor method for a GetMovieDetails response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieDetailsJSON502Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        502,
		contentType: "application/json",
	}
}

// GetMovieReviewsJSON200Response is a constructor method for a GetMovieReviews response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieReviewsJSON200Response(body ReviewList) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetMovieReviewsJSON400Response is a constructor method for a GetMovieReviews response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieReviewsJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetMovieReviewsJSON500Response is a constructor method for a GetMovieReviews response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieReviewsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetMovieReviewsJSON502Response is a constructor method for a GetMovieReviews response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieReviewsJSON502Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        502,
		contentType: "application/json",
	}
}

// SearchMovieJSON200Response is a constructor method for a SearchMovie response.
// A *Response is returned with the configured status code and content type from the spec.
func SearchMovieJSON200Response(body MovieList) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// SearchMovieJSON400Response is a constructor method for a SearchMovie response.
// A *Response is returned with the configured status code and content type from the spec.
func SearchMovieJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// SearchMovieJSON500Response is a constructor method for a SearchMovie response.
// A *Response is returned with the configured status code and content type from the spec.
func SearchMovieJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// SearchMovieJSON502Response is a constructor method for a SearchMovie response.
// A *Response is returned with the configured status code and content type from the spec.
func SearchMovieJSON502Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        502,
		contentType: "application/json",
	}
}

// GetMovieVideosJSON200Response is a constructor method for a GetMovieVideos response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieVideosJSON200Response(body VideoList) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetMovieVideosJSON400Response is a constructor method for a GetMovieVideos response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieVideosJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetMovieVideosJSON500Response is a constructor method for a GetMovieVideos response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieVideosJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetMovieVideosJSON502Response is a constructor method for a GetMovieVideos response.
// A *Response is returned with the configured status code and content type from the spec.
func GetMovieVideosJSON502Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        502,
		contentType: "application/json",
	}
}

// GetCategoryJSON200Response is a constructor method for a GetCategory response.
// A *Response is returned with the configured status code and content type from the spec.
func GetCategoryJSON200Response(body MovieList) *Response {
	return &Response{
		body:        body,
		Code:        200,
		contentType: "application/json",
	}
}

// GetCategoryJSON400Response is a constructor method for a GetCategory response.
// A *Response is returned with the configured status code and content type from the spec.
func GetCategoryJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        400,
		contentType: "application/json",
	}
}

// GetCategoryJSON500Response is a constructor method for a GetCategory response.
// A *Response is returned with the configured status code and content type from the spec.
func GetCategoryJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        500,
		contentType: "application/json",
	}
}

// GetCategoryJSON502Response is a constructor method for a GetCategory response.
// A *Response is returned with the configured status code and content type from the spec.
func GetCategoryJSON502Response(body Error) *Response {
	return &Response{
		body:        body,
		Code:        502,
		contentType: "application/json",
	}
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get movie cast by ID
	// (GET /cast/{movieId})
	GetMovieCast(w http.ResponseWriter, r *http.Request, movieID string) *Response
	// Get movie details by ID
	// (GET /details/{movieId})
	GetMovieDetails(w http.ResponseWriter, r *http.Request, movieID string) *Response
	// Get movie reviews by ID
	// (GET /reviews/{movieId})
	GetMovieReviews(w http.ResponseWriter, r *http.Request, movieID string, params GetMovieReviewsParams) *Response
	// Search for movie
	// (GET /search)
	SearchMovie(w http.ResponseWriter, r *http.Request, params SearchMovieParams) *Response
	// Get movie videos by ID
	// (GET /videos/{movieId})
	GetMovieVideos(w http.ResponseWriter, r *http.Request, movieID string) *Response
	// Get currently playing movies
	// (GET /{category})
	GetCategory(w http.ResponseWriter, r *http.Request, category string, params GetCategoryParams) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// GetMovieCast operation middleware
func (siw *ServerInterfaceWrapper) GetMovieCast(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "movieId" -------------
	var movieID string

	if err := runtime.BindStyledParameter("simple", false, "movieId", chi.URLParam(r, "movieId"), &movieID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "movieId"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetMovieCast(w, r, movieID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetMovieDetails operation middleware
func (siw *ServerInterfaceWrapper) GetMovieDetails(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "movieId" -------------
	var movieID string

	if err := runtime.BindStyledParameter("simple", false, "movieId", chi.URLParam(r, "movieId"), &movieID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "movieId"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetMovieDetails(w, r, movieID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetMovieReviews operation middleware
func (siw *ServerInterfaceWrapper) GetMovieReviews(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "movieId" -------------
	var movieID string

	if err := runtime.BindStyledParameter("simple", false, "movieId", chi.URLParam(r, "movieId"), &movieID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "movieId"})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMovieReviewsParams

	// ------------- Required query parameter "page" -------------

	if err := runtime.BindQueryParameter("form", true, true, "page", r.URL.Query(), &params.Page); err != nil {
		err = fmt.Errorf("invalid format for parameter page: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "page"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetMovieReviews(w, r, movieID, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// SearchMovie operation middleware
func (siw *ServerInterfaceWrapper) SearchMovie(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchMovieParams

	// ------------- Required query parameter "queryString" -------------

	if err := runtime.BindQueryParameter("form", true, true, "queryString", r.URL.Query(), &params.QueryString); err != nil {
		err = fmt.Errorf("invalid format for parameter queryString: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "queryString"})
		return
	}

	// ------------- Required query parameter "page" -------------

	if err := runtime.BindQueryParameter("form", true, true, "page", r.URL.Query(), &params.Page); err != nil {
		err = fmt.Errorf("invalid format for parameter page: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "page"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.SearchMovie(w, r, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetMovieVideos operation middleware
func (siw *ServerInterfaceWrapper) GetMovieVideos(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "movieId" -------------
	var movieID string

	if err := runtime.BindStyledParameter("simple", false, "movieId", chi.URLParam(r, "movieId"), &movieID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "movieId"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetMovieVideos(w, r, movieID)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetCategory operation middleware
func (siw *ServerInterfaceWrapper) GetCategory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "category" -------------
	var category string

	if err := runtime.BindStyledParameter("simple", false, "category", chi.URLParam(r, "category"), &category); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "category"})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCategoryParams

	// ------------- Required query parameter "page" -------------

	if err := runtime.BindQueryParameter("form", true, true, "page", r.URL.Query(), &params.Page); err != nil {
		err = fmt.Errorf("invalid format for parameter page: %w", err)
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "page"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetCategory(w, r, category, params)
		if resp != nil {
			if resp.body != nil {
				render.Render(w, r, resp)
			} else {
				w.WriteHeader(resp.Code)
			}
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:    "/",
		BaseRouter: chi.NewRouter(),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Get("/cast/{movieId}", wrapper.GetMovieCast)
		r.Get("/details/{movieId}", wrapper.GetMovieDetails)
		r.Get("/reviews/{movieId}", wrapper.GetMovieReviews)
		r.Get("/search", wrapper.SearchMovie)
		r.Get("/videos/{movieId}", wrapper.GetMovieVideos)
		r.Get("/{category}", wrapper.GetCategory)
	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXS2/bRhD+K4tpgV4IU05SwOCxcREIfbk20Evgw4ocSZuQu+vZoQxB0H8v9iFRD8qW",
	"gTaJHJ1EcWdnvpn9vtnhAkrTWKNRs4NiAa6cYiPD43vp2P8qxia8+JFwDAX8kHdb8mSf3yA5o2GZAc8t",
	"QgGSSM79/1+JDPntloxFYoXBWYPOyQn6x7TDMSk9geUyA8KHVhFWUHxcG94vM/jDzBReI0tVu32XI1l+",
	"rsjYHp8ZVJKxd2GCmuL+daJ7Nrs5TU2Dth99Blo2/QtmhjRT+Ni7aI1jpN4lkuyfigWMDTWSoYDKtKMa",
	"YY1Mt80IKRi3mtUWAKUZJ35xp7ApYgK8DpNKtQF3I9+sK3IXal3D+zUeM/qEJcPqyH5XkUrb57VTwTVO",
	"D9O1Nbuj2ReC3BAGuD3nxYZlfSMn6I6pS0x0Y08H6GCGq+B7SR7knar6c/+a9NmphKogO54mfbVJbWGv",
	"KuVUkiwPIT5YAqtKbumIppGwruyzjYB9MG8PHF5pNKPmZ8r6NJR1vVbODgP4v2Vy+3UE8o+q0OznVSv9",
	"ub/bKq77z59JqnqLNCNjapR6D2P0kcUg3caD8FalP6qOMaG9MnoMSo9DqhW6kpRl5dkP0irBRjS+U4gR",
	"mUeHJHwnRe0llhKGrXXIYIbkooPBxeDiMjQBi1paBQW8vbi8eOs5LnkaEOeldJwvgpNhtfSvJhiS8lWX",
	"HsqwggI+IIeWFe53v59kg4zkoPi4C/zPtkFSpRheCzNO+NkI79fnCkUIv2oOKYNhBZuHwdRilgaLPrnc",
	"B/ZYo13kxZvBYEd70tpalSGD/FPqJ52/p04q5BgOZjuvv37zxXz3H0aKY05PqF9kJW7xoUUX2Pbu8mqf",
	"H8OfGiEFo7QmGP38JYANNSNpWYs7pBmSSIY++psvU5YPkvExKCcD1zaNpHnkZ2KaJ7QYzcXwOpjkVZz8",
	"XsDx1az4ymm+leuZ7idK90TvTcbHqfIljI93/DfB+Gw3qB8cRJo1U5SHFmnehUmjxbehqo2h7KypE9VU",
	"EtCmphxKKqcHhXQXloOWnhPR3568InGxn9Dh793K4vvRTvfZf5bOSUkn0l+MDUUFRc3M/BfPS66h8In0",
	"6ueu7tPxzPITvSAiszfvh0UpGSeG5k+y/H0yeo7iK7s1wd2TDC87t+fL4iyjE5BR2RKh5noubC3nSk8S",
	"zaMnFwBHYbRUQwFTZlvkeW1KWU+N4+JqcDXIpVWwvF/+GwAA//9nkD6FjxoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
