openapi: 3.1.3
info:
  title: movie browser
  description: api to movie browser backend
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
paths:
  /nowplaying:
    get:
      summary: Get currently playing movies
      operationId: getNowPlaying
      parameters:
        - in: query
          name: page
          schema:
            type: string
          required: true
          description: page number
      responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/MovieList"
          "400":
            description: Bad Request
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
          "418":
            description: I'm a teapot
          "500":
            description: Internal Server Error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
          "502":
            description: Bad Gateway
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /popular:
    get:
      summary: Get popular movies
      operationId: getPopular
      parameters:
        - in: query
          name: page
          schema:
            type: string
          required: true
          description: page number
      responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/MovieList"
          "400":
            description: Bad Request
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
          "418":
            description: I'm a teapot
          "500":
            description: Internal Server Error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
          "502":
            description: Bad Gateway
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /search:
    get:
      summary: Search for movie 
      operationId: searchMovie
      parameters:
        - in: query
          name:  queryString
          schema:
            type: string
          required: true
          description: Query string
        - in: query
          name: page
          schema:
            type: string
          required: true
          description: page number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieList"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /details/{movieId}:
    get:
      summary: Get movie details by ID
      operationId: getMovieDetail
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Numeric ID of movie to get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovieDetails"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /reviews/{movieId}:
    get:
      summary: Get movie reviews by ID
      operationId: getMovieReviews
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Numeric ID of movie to get
        - in: query
          name: page
          schema:
            type: string
          required: true
          description: page number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReviewList"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /videos/{movieId}:
    get:
      summary: Get movie videos by ID
      operationId: getMovieVideos
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Numeric ID of movie to get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VideoList"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cast/{movieId}:
    get:
      summary: Get movie cast by ID
      operationId: getMovieCast
      parameters:
        - in: path
          name: movieId
          schema:
            type: string
          required: true
          description: Numeric ID of movie to get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cast"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "418":
          description: I'm a teapot
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      properties:
        message:
          type: string
      required:
        - message
    MoviePreview:
      type: object
      properties:
        id: 
          type: integer
          format: int32
        poster: 
          type: string
        name:
          type: string
        rating:
          type: number
          format: float
        date:
          type: string
      required:
        - id
        - poster
        - name
        - rating
        - date
    MovieDetails:
      type: object
      properties:
        poster: 
          type: string
        name:
          type: string
        rating:
          type: number
          format: float
        date:
          type: string
        overview:
          type: string
        homepage:
          type: string
        backdrop:
          type: string
      required:
        - poster
        - name
        - rating
        - date
        - overview
        - homepage
        - backdrop
    MovieList:
      type: object
      properties:
        page:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        results:
          type: array
          items:
            $ref: "#/components/schemas/MoviePreview"
      required:
        - page
        - totalPages
        - results
    Review:
      type: object
      properties:
        rating: 
          type: string
        content:
          type: string
      required:
        - rating
        - content
    ReviewList: 
      type: object
      properties:
        page:
          type: integer
          format: int32
        totalPages:
          type: integer
          format: int32
        results:
          type: array
          items:
            $ref: "#/components/schemas/Review"
      required:
        - page
        - totalPages
        - results
    Video:
      type: object
      properties:
        title:
          type: string
        link:
          type: string
        trailer:
          type: boolean
      required:
        - title
        - link
        - trailer
    VideoList:
      type: array
      items:
        $ref: "#/components/schemas/Video"
    Person:
      type: object
      properties:
        name:
          type: string
        picture:
          type: string
        character:
          type: string
      required:
        - name
        - picture
        - character
    Cast:
      type: array
      items:
        $ref: "#/components/schemas/Person"